// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmgtvwjgfnhuxruwhlwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtZ3R2d2pnZm5odXhydXdobHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTE1NTEsImV4cCI6MjA2ODc4NzU1MX0.O_B1VzGO0vW47kfrAEYtrkiavCtWiu3DDWsH6LhFa_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});